### ISSUE TITLE
About .pth file that computer_center.py need 

### ISSUE THREAD

**Issue by KZF-kzf** [zhangdoudou123/SemFew#4]
Hello, I am executing the compute_center.py file, and I noticed that he needs a backbone_{Dataset}.pth file, is it the weight of SwinT/ResNet-{Dataset}.pth that you gave? Are these weights obtained by pre-training on the base set? Looking forward to your answer.

**Comment by zhangdoudou123** [comment]
Yes, you are right. These weights are obtained by base split training and are used to compute approximate class centers.

**Comment by KZF-kzf** [comment]
Thank you very much for your answer. I tested according to the weight, but can't repetition you on MiniImageNet results: https://github.com/zhangdoudou123/SemFew/issues/5. Is there a problem with my lab setup?

**Comment by caoziyang1997** [comment]
> 你好，我在执行compute_center.py文件，发现他需要一个backbone_{Dataset}.pth文件，你给的是不是SwinT/ResNet-{Dataset}.pth的权重？这些权重是在基集上预训练得到的吗？期待你的回答。

Traceback (most recent call last):
  File "compute_center.py", line 8, in <module>
    from data.tiered_imagenet import tieredImageNet
  File "/home/czy/project/zhaojia/SemFew/data/tiered_imagenet.py", line 53, in <module>
    id2wnids = [x.strip() for x in open(os.path.join(IMAGE_PATH, 'find_labels.csv'), 'r').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/home/czy/project/datasets/tiered-imagenet/find_labels.csv'

请问这个find_labels.csv在哪下载
