### ISSUE TITLE
Hello, first of all, thank you very much for your excellent work. I am very interested in your work, so I tried to reproduce your work, but I encountered some problems after replicating the result. If you can see it, I hope you can help me solve my doubts.

### ISSUE THREAD

**Issue by myl666666** [zhangdoudou123/SemFew#7]
[SemFew.txt](https://github.com/user-attachments/files/16402622/SemFew.txt)

**Comment by DruryXu** [comment]
Please refer to my replies in #5

**Comment by myl666666** [comment]
Thank you very much for your reply. I want to conduct research on the experiment on resnet network. May I ask how to obtain the checkpoint files of the training four data sets on resnet network? I saw that the checkpoint files of imagenet and cifar data sets you uploaded on github seem to be the only ones. Does the FC100 also use cifar100_semantic_clip_gpt.pth file?
Finally, I wish you good health and success in your work

**Comment by DruryXu** [comment]
What is the exact meaning of "checkpoint" in your question? If you are talking about semantic features, then there are only two semantic features files, because MiniImageNet and TieredImageNet both come from ImageNet, while CIFAR-FS and FC100 both come from CIFAR-100. Therefore, it is true that FC100 also use cifar100_semantic_clip_gpt.pth file.

**Comment by DruryXu** [comment]
Sorry, I made a mistake with the reference in my reply yesterday. Please see my edited reply.

**Comment by myl666666** [comment]
Thank you very much for taking time out of your busy schedule to solve my doubts. The accuracy achieved by my FC100 dataset on the Resnet network is as follows:
1-shot:
7-28 23:24:47, 026-meta_test. py[line:49] -INFO: {'test_batch': 600, 'shot': 1, 'query': 15, 'test_way': 5, 'center': 'mean', 'seed': 13, 'feat_size': 640, 'semantic_size': 512, 'num_workers': 8, 'mode': 'clip', 'text_type':  'gpt', 'dataset': 'FC100', 'backbone': 'resnet', 'model_path':  'E:/miaodashuai/SemFew-main/SemFew-main/ResNet-FC100.pth', 'work_dir': 'resnet_FC100_clip_gpt_mean_1'}
2024-07-28 23:24:48, 495-meta_test. py[line:103] -INFO: best epoch: 45 65.284446
2024-07-28 23:24:48, 496-meta_test. py[line:104] -INFO: best k: 0.400000
2024-07-28 23:25:20,453 - meta_test.py[line:141] -info: max |k: 0.4 |mix acc: 48.33+0.75% |gap: 4.48
2024-07-28 23:25:20,453 - meta_test.py[line:143] -info: ACC:|proto acc: 43.85+0.74% |gen acc: 42.66+0.73%
5-shot:
7-29 00:48:20, 416-meta_test. py[line:49] -INFO: {'test_batch': 600, 'shot': 5, 'query': 15, 'test_way': 5, 'center': 'mean', 'seed': 13, 'feat_size': 640, 'semantic_size': 512, 'num_workers': 8, 'mode': 'clip', 'text_type':  'gpt', 'dataset': 'FC100', 'backbone': 'resnet', 'model_path':  'E:/miaodashuai/SemFew-main/SemFew-main/ResNet-FC100.pth', 'work_dir': 'resnet_FC100_clip_gpt_mean_5'}
2024-07-29 00:48:21,636 - meta_test.py[line:103] -info: best epoch: 32 82.213335
2024-07-29 00:48:21,636 -meta_test. py[line:104] -INFO: best k: 0.790000
2024-07-29 00:48:56, 614-meta_test. py[line:141] -INFO: max |k: 0.79 |mix acc: 60.42+0.78% |gap: 0.66
2024-07-29 00:48:56,614 -meta_test. py[line:143] -INFO: ACC:|proto acc: 59.77+0.78% |gen acc: 43.02+0.73%
Is the above result normal? I conducted the test according to your experimental Settings, the pth file should be corresponding and the path is correct. If there are other neglected problems, please point out.
Thanks again for your work and guidance!

**Comment by KZF-kzf** [comment]
@myl666666 can you reproduce their results on FC100 or CIFAR_FS now?

**Comment by myl666666** [comment]
> 您现在可以在 FC100 或 CIFAR_FS 上重现他们的结果吗？
i can not ,sorry

**Comment by DruryXu** [comment]
> @myl666666 can you reproduce their results on FC100 or CIFAR_FS now?

Could you please share your reproduction results for helping us locating where the problem comes from?

**Comment by caoziyang1997** [comment]
> > @myl666666你现在可以在 FC100 或 CIFAR_FS 上重现他们的结果吗？
> 
> 您能否分享一下您的复现结果，帮助我们定位问题出在哪里？

Traceback (most recent call last):
  File "compute_center.py", line 8, in <module>
    from data.tiered_imagenet import tieredImageNet
  File "/home/czy/project/zhaojia/SemFew/data/tiered_imagenet.py", line 53, in <module>
    id2wnids = [x.strip() for x in open(os.path.join(IMAGE_PATH, 'find_labels.csv'), 'r').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/home/czy/project/datasets/tiered-imagenet/find_labels.csv'
请问这个问题怎么解决

**Comment by KitABC12** [comment]
> 您现在可以在 FC100 或 CIFAR_FS 上重现他们的结果吗？

Hello, I am currently using the CIFAR-FS dataset on ResNet for 5-way 1-shot tasks and can only achieve an accuracy of around 82.8%. Can your results reach the 83.65% mentioned in the paper?

**Comment by qttis** [comment]
> > 您现在可以在 FC100 或 CIFAR_FS 上重现他们的结果吗？
> 
> Hello, I am currently using the CIFAR-FS dataset on ResNet for 5-way 1-shot tasks and can only achieve an accuracy of around 82.8%. Can your results reach the 83.65% mentioned in the paper?

82.52%

**Comment by linjieb** [comment]
> > [@myl666666](https://github.com/myl666666) can you reproduce their results on FC100 or CIFAR_FS now?
> 
> Could you please share your reproduction results for helping us locating where the problem comes from?

[test_CIFAR-FS.txt](https://github.com/user-attachments/files/18935559/test_CIFAR-FS.txt)

[test_FC100.txt](https://github.com/user-attachments/files/18935562/test_FC100.txt)

[test_MiniImageNet.txt](https://github.com/user-attachments/files/18935563/test_MiniImageNet.txt)
dear author,could you please help me solve the problems why my results are so bad?

**Comment by LiuMeilin7195** [comment]
> > > [@myl666666](https://github.com/myl666666) can you reproduce their results on FC100 or CIFAR_FS now?
> > 
> > 
> > Could you please share your reproduction results for helping us locating where the problem comes from?
> 
> [test_CIFAR-FS.txt](https://github.com/user-attachments/files/18935559/test_CIFAR-FS.txt)
> 
> [test_FC100.txt](https://github.com/user-attachments/files/18935562/test_FC100.txt)
> 
> [test_MiniImageNet.txt](https://github.com/user-attachments/files/18935563/test_MiniImageNet.txt) dear author,could you please help me solve the problems why my results are so bad?

My replication results on these three datasets are very close to the results provided in your txt file. May I ask if you have achieved better replication results?

**Comment by linjieb** [comment]
> > > > [@myl666666](https://github.com/myl666666) can you reproduce their results on FC100 or CIFAR_FS now?
> > > 
> > > 
> > > Could you please share your reproduction results for helping us locating where the problem comes from?
> > 
> > 
> > [test_CIFAR-FS.txt](https://github.com/user-attachments/files/18935559/test_CIFAR-FS.txt)
> > [test_FC100.txt](https://github.com/user-attachments/files/18935562/test_FC100.txt)
> > [test_MiniImageNet.txt](https://github.com/user-attachments/files/18935563/test_MiniImageNet.txt) dear author,could you please help me solve the problems why my results are so bad?
> 
> My replication results on these three datasets are very close to the results provided in your txt file. May I ask if you have achieved better replication results?

No,may be the code provided is not complete
